// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.188
// </auto-generated>
// ------------------------------------------------------------------------------
namespace TraceLogger
{
    static class Vsix
    {
        public const string Id = "a299a65a-dcf1-4271-96ca-4fd4c4f80b90";
        public const string Name = "Debug Trace Logger";
        public const string Description = @"Allows Visual Studio extension authors to easily see any debug and trace statements in a custom Output Window pane.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Mads Kristensen";
        public const string Tags = "debug, trace, logging, diagnostics";
    }
}
